models/cart.py
from db_connect import db


class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    store_id = db.Column(db.Integer, db.ForeignKey('store.id'), nullable=False)
    food_id = db.Column(db.Integer, db.ForeignKey('food.id'), nullable=False)
    food_count = db.Column(db.Integer, nullable=False)

models/food.py
from db_connect import db
from sqlalchemy.orm import relationship

# from models.food import Food
# flask run - 자동으로 db 테이블 형성

class Food(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    store_id = db.Column(db.Integer, db.ForeignKey('store.id'), nullable=False)
    fname = db.Column(db.String(100), nullable=False)
    fprice = db.Column(db.Integer, nullable=False)
    finfo = db.Column(db.String(10000), nullable=False)
    furl = db.Column(db.String, nullable=False)

    def __init__(self, store_id, fname, fprice, finfo, furl):
        self.store_id = store_id
        self.fname = fname
        self.fprice = fprice
        self.finfo = finfo
        self.furl = furl


# food1 = Food(store_id=1, 
#             fname="후라이드 치킨", fprice=19000,
#             finfo="환상의 바삭함", furl="https://news.nateimg.co.kr/orgImg/it/2021/12/18/2021121800550_0.jpg")

# food2 = Food(store_id=1, 
#             fname="양념 치킨", fprice=21000,
#             finfo="환상의 고소함", furl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKg2-F6ZiWZiiZIke3U80HrkuZsTlrfcV3Yg&usqp=CAU")

# food3 = Food(store_id=1, 
#             fname="치즈가루 치킨", fprice=21000,
#             finfo="환상의 달달함", furl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQY0Utdp7qMQwYg6DJBpMpeXQtE7CinD66BQQ&usqp=CAU")

# db.session.add(food1)
# db.session.add(food2)
# db.session.add(food3)

# db.session.commit()

models/order.py
from db_connect import db
from sqlalchemy.orm import relationship



class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    store_id = db.Column(db.Integer, db.ForeignKey('store.id'), nullable=False)
    total_price = db.Column(db.Integer, nullable=False)
    order_address = db.Column(db.String(100), nullable=False)
    order_date = db.Column(db.String(30), nullable=False)



class OrderDetail(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer, db.ForeignKey('order.id'), nullable=False)
    food_name = db.Column(db.String, nullable=False)
    food_count = db.Column(db.Integer, nullable=False)
    food_price = db.Column(db.Integer, nullable=False)
    food_img = db.Column(db.String(50))

models/store.py
from db_connect import db

# shop, fname, finfo, fprice, furl = 찬희님
# contents, title, image_url = store
class Store(db.Model): 
    id = db.Column(db.Integer, primary_key=True) 
    title = db.Column(db.String, nullable=False) 
    contents = db.Column(db.String, nullable=False) 
    image_url = db.Column(db.String, nullable=False) 

views/cart.py
from flask import Blueprint, render_template, request, url_for, session, redirect, jsonify
from models.cart import Cart
from models.user import User
from models.store import Store
from models.food import Food
# from models.food import Food
from db_connect import db
from myJWT import isTokenVaild, getUserEmail  # 토큰 유효성 검증 함수 사용하기 위해

from datetime import datetime
from pytz import timezone


bp = Blueprint('cart', __name__, url_prefix='/cart')

@bp.route('/', methods=['GET', 'POST'])
def cart():
    if request.method == 'GET':
        # 유효성 검증
        if (isTokenVaild() == False):  # 현재 쿠키의 토큰이 유효하지 않으면
            print("로그인 하세요.")
            return redirect("/login")  # 다시 로그인 페이지로
        
        context = {
            'cart_list': []
        }
                
        # token을 가져와 user 판별.
        user_email = getUserEmail()
        user_id = User.query.filter_by(email=user_email).first().id
        context['user_id'] = user_id
        print('cart_user_id : ', user_id)
        
        cart_list = Cart.query.filter_by(user_id=user_id).all()

        
        for cart in cart_list:
            food = Food.query.filter_by(id=cart.food_id).first()
            store = Store.query.filter_by(id=cart.store_id).first()
            context['cart_list'].append({
                'cart_id': cart.id,
                'store_id': store.id,
                'store_name': store.title,
                'food_id': food.id,
                'food_name': food.fname,
                'food_image': food.furl,
                'food_price': food.fprice,
                'food_count': cart.food_count,
            })
        
        
        return render_template("cart.html", data=context)
    elif request.method == 'POST':
        user_email = getUserEmail()
        user_id = User.query.filter_by(email=user_email).first().id

        data = request.json  # 클라이언트에서 전달한 JSON 데이터 받기
        print("cart_data : ", data)
        store_id = data.get('store_id')
        food_id = data.get('food_id')
        food_count = data.get('food_count')

        new_cart = Cart(user_id=user_id, store_id=store_id, food_id=food_id, food_count=food_count)
        db.session.add(new_cart)
        db.session.commit()

        return jsonify({'result': 'success'})
    
    elif request.method == 'DELETE':

        return None

views/food.py
from flask import Blueprint, render_template, request, url_for, session, redirect 
from models.food import Food


bp = Blueprint('food', __name__, url_prefix='/food')

@bp.route('/<int:store_id>/', methods=['GET', 'POST'])
def food(store_id):
    if request.method == 'GET':    
        print('store_id : ', store_id)
        # store_list 가져오기
        foods = Food.query.filter_by(store_id=store_id).all()
        
        return render_template("food.html", data=foods, store_id=store_id)
    

# @bp.route('/', methods=['GET', 'POST'])
# def food():
    
#     if request.method == 'GET':
    
#         foods =Food.query.all()
#         print(foods)
#         return render_template('food.html', data=foods)

#     else:
#         print("else")
#         return None

views/login.py
import datetime
from flask import Blueprint, jsonify, render_template, request, url_for, session, redirect, flash
from jwt import encode
import jwt
from config import JWT_SECRET_KEY
from models.user import User
from encryptor import check_hash

bp = Blueprint('login', __name__, url_prefix='/login')


@bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password', False)
        print(email)
        print(password)

        user = User.query.filter_by(email=email).first()

        if user and check_hash(user.password, password):  # 로그인이 유효한 경우
            # TypeError: Object of type datetime is not JSON serializable 해결하기 위해 string으로 변환
            dateString = (datetime.datetime.now()
                          + datetime.timedelta(60*60*1)).strftime("%Y-%m-%d %H:%M:%S")
            print("asdfasdf", flush=True)

            payload = {'email': email, 'expire': dateString}
            # jwt 토큰 생성
            token = encode(payload, JWT_SECRET_KEY,
                           algorithm='HS256')

            # 응답 jsonify 객체 반환
            return jsonify({'result': 'success', 'token': token})

        else:
            print("비밀번호가 틀림")
            return jsonify({'result': 'fail', 'error': "비밀번호가 틀렸습니다."})

    print("get 요청시")
    return render_template('login.html')

views/order.py
from flask import Blueprint, render_template, request, url_for, session, redirect 
from models.order import Order, OrderDetail
from models.user import User
from models.cart import Cart
from models.food import Food
from models.store import Store
from db_connect import db
from myJWT import isTokenVaild, getUserEmail
from datetime import datetime
from pytz import timezone


bp = Blueprint('order', __name__, url_prefix='/order')

@bp.route('/list', methods=['GET', 'POST'])
def order_list():
    """
    주문 목록
    """
    # 유효성 검증
    if (isTokenVaild() == False):  # 현재 쿠키의 토큰이 유효하지 않으면
        print("로그인 하세요.")
        return redirect("/login")  # 다시 로그인 페이지로
    
    if request.method == 'GET':    
        # token을 가져와 user 판별.
        user_email = getUserEmail()
        user_id = User.query.filter_by(email=user_email).first().id
        
        # 주문 목록 가져오기
        orders = Order.query.filter_by(user_id=user_id).all()

        context = {
            "order": []
        }

        

        for order in orders:
            order_details = OrderDetail.query.filter_by(order_id=order.id).all()
            result = {
                "order_id": order.id,
                "order_date": order.order_date,
                "order_address": order.order_address,
            }
            foods = []
            for order_detail_food in order_details:
                food = {
                    "id": order_detail_food.id,
                    "food_name": order_detail_food.food_name,
                    "food_price": order_detail_food.food_price,
                    "food_img": order_detail_food.food_img,
                }
                foods.append(food)
            result["food"] = foods
            context["order"].append(result)
        # print(context)

        return render_template("order_list.html", data=context)
    
@bp.route('/', methods=['GET', 'POST'])
def order():
    """
    주문
    """
    # 유효성 검증
    if (isTokenVaild() == False):  # 현재 쿠키의 토큰이 유효하지 않으면
        print("로그인 하세요.")
        return redirect("/login")  # 다시 로그인 페이지로
    
    if request.method == 'POST':
        # token을 가져와 user 판별.
        user_email = getUserEmail()
        user_id = User.query.filter_by(email=user_email).first().id

        data = request.get_json()
        print('order_data : ', data)
        store_id = data['cart_list'][0]['store_id']
        order_date = datetime.now(timezone('Asia/Seoul')).strftime("%Y-%m-%d %H:%M:%S")
        total_price = data['total_price']
        order_address = data['address']
        print("order_address : ", order_address)

        print('user_id, store_id, order_date, total_price : ', user_id, store_id, order_date, total_price)
        [ print("data['food'] : ", i) for i in data['cart_list'][0]['food']] 

        order = Order(user_id=user_id, store_id=store_id, order_address=order_address, order_date=order_date, total_price=total_price)
        db.session.add(order)
        db.session.commit()

        latest_order = Order.query.order_by(Order.id.desc()).first()
        for food_data in data['cart_list'][0]['food']:
            food_name = food_data['food_name']
            food_count = food_data['food_count']
            food_price = food_data['food_price']
            food_image = food_data['food_image']
            print('food_name : ', food_name)
            print('food_count : ', food_count)
            print('food_price : ', food_price)

            order_detail = OrderDetail(order_id=latest_order.id, food_name=food_name, food_count=food_count, food_price=food_price, food_img=food_image)
            db.session.add(order_detail)

        db.session.commit()

        # 주문이 완료되면 cart 테이블의 데이터를 삭제
        cart_delete = Cart.query.filter_by(user_id=user_id).all()
        for item in cart_delete:
            db.session.delete(item)
        db.session.commit()

        return redirect(url_for('order.order_list'))
    
    elif request.method == "GET":
        context = {
            'cart_list' : []
        }

        # token을 가져와 user 판별.
        user_email = getUserEmail()
        user_id = User.query.filter_by(email=user_email).first().id

        cart_list = Cart.query.filter_by(user_id=user_id).all()
        # cart_list에 담긴 food 정보 찾기
        foods = []
        for cart in cart_list:
            food_id = cart.food_id 
            food = Food.query.filter_by(id=food_id).first()
            store_id = cart.store_id
            store = Store.query.filter_by(id=store_id).first()
            foods.append({
                'id':food.id,
                'food_name': food.fname,
                'food_price': food.fprice,
                "food_image": food.furl,
                'food_count' : cart.food_count,
            })

            context['cart_list'].append({
                "store_id": store.id,
                "store_name": store.title,
                "food": foods,
            })
            


        total_price = 0  # 총 가격 초기화

        for cart in context['cart_list']:
            for food in cart['food']:
                # 각 음식 항목의 수량과 가격을 곱하여 총 가격을 계산
                total_price += food['food_price'] * food['food_count']

        context['total_price'] = total_price
        
        return render_template("order.html", data=context)

views/signup.py
# 1. import Blueprint
from flask import Blueprint, jsonify, render_template, request, url_for, session, redirect, flash
from models.user import User
from db_connect import db
from encryptor import check_hash, encrypt
# 2. Blueprint 초기화
# 'signup': Blueprint의 이름
#  url_prefix='/signup': signup으로 시작하는 모든 URL이 묶임.
bp = Blueprint('signup', __name__, url_prefix='/signup')


# 3. app을 bp로 교체
@bp.route('/', methods=['GET', 'POST'])
def signUp():
    print("signup페이지 이동")
    if request.method == 'POST':
        # print(request.form)
        username = request.form['username']
        nickname = request.form['nickname']
        email = request.form['email']
        password = request.form['password']

        # print(username, nickname, email, password)
        if checkEmailDuplicate(email):
            # 중복 이메일 있음
            print("이메일 중복", "error")
            return jsonify({'result': 'false', 'error': '이미 가입한 이메일입니다.'})
        elif checkNicknameDuplicate(nickname):
            # 중복 닉네임 있음
            print("닉네임 중복", "error")
            return jsonify({'result': 'false', 'error': '존재하는 닉네임입니다.'})
        else:
            # 비밀번호 암호화
            print("회원가입 유효성 검증 완료")
            hashedPassword = encrypt(password=password)
            print("해시된 비밀번호 : ", hashedPassword)
            newUser = User(username=username, nickname=nickname,
                           email=email, password=hashedPassword)
            db.session.add(newUser)
            db.session.commit()
            print('회원가입이 완료되었습니다!', 'success')
            return jsonify({'result': 'success'})

    print("get 요청시")
    return render_template('signup.html')


def checkNicknameDuplicate(nickname):
    if User.query.filter_by(nickname=nickname).first():
        print(User.query.filter_by(nickname=nickname).first())
        return True
    return False


def checkEmailDuplicate(email):
    if User.query.filter_by(email=email).first():
        return True
    return False

views/store.py
from flask import Blueprint, render_template, request, url_for, session, redirect 
from models.store import Store


bp = Blueprint('store', __name__, url_prefix='/store')

@bp.route('/', methods=['GET', 'POST'])
def store():
    if request.method == 'GET':    

        # store_list 가져오기
        store_list = Store.query.all()
        
        return render_template("stores.html", data=store_list)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Hanghae</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="../static/assets/img/apple-touch-icon.png" rel="icon">
  <link href="../static/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="../static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="../static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">


  <!-- Template Main CSS File -->
  <link href="../static/assets/css/main.css" rel="stylesheet">

  {% block head %}

  {% endblock %}
  <title>{% block title %}{% endblock %}</title>
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="/store" class="logo d-flex align-items-center me-auto me-lg-0">
        <h1>Hanghae-eats<span>.</span></h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="/store">Menu</a></li>
          <li><a href="/cart">Cart</a></li>
          <li><a href="/order/list">OrderList</a></li>
        </ul>
      </nav><!-- .navbar -->

      <a class="btn-book-a-table" href="/login">Login</a>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header>
  <!-- End Header -->


  <main id="main" class="mt-5">
    {% block page_content %}
    
    {% endblock %}
  </main>
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-geo-alt icon"></i>
          <div>
            <h4>Address</h4>
            <p>
              항해, 부둣가 99번지 <br>
              스파르타 빌딩 13<br>
            </p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Reservations</h4>
            <p>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> hanghae@hanghae.com<br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Opening Hours</h4>
            <p>
              <strong>Mon-Sat: 9AM</strong> - 9PM<br>
              Sunday: Closed
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="../../static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  

  <!-- Template Main JS File -->
  <script src="../../static/assets/js/main.js"></script>

</body>

</html>

templates/cart.html
{% extends 'base.html' %}

{% block title%}
장바구니
{% endblock %}

{% block page_content %}
<div class="container mt-5" style="min-height: 400px">
    <h1 class="mt-3">장바구니</h1>
    <div class="card mb-3">
        <div class="card-body">
            <ul>
                {% for cart in data['cart_list'] %}
                    <h2 class="stats-item">{{ cart.store_name }}</h2>
                    <ul class="list-group">
                        
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-md-3">
                                        <!-- 이미지를 추가하려면 여기에 이미지 태그를 추가하세요 -->
                                        <img src="{{ cart.food_image }}" width="280px" height="130px" style="vertical-align: middle;">
                                    </div>
                                    <div class="col-md-9">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <div class="float-right mb-2">음식</div>
                                                <div class="float-right mb-2">음식이름</div>
                                                <div class="float-right mb-2">음식가격</div>
                                                <div class="float-right mb-2">음식수량</div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="mb-2">{{ cart.food_id }}</div>
                                                <div class="mb-2">{{ cart.food_name }}</div>
                                                <div class="mb-2">{{ cart.food_price }}</div>
                                                <div class="mb-2">{{ cart.food_count }}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                    </ul>
                {% endfor %}
                </div>
            </div>
            <button type="button" class="btn btn-danger mb-3" id="orderButton">주문하기</button>
        </div>

        <script>
            document.addEventListener("DOMContentLoaded", function () {
                const orderButton = document.getElementById("orderButton");
                
                orderButton.addEventListener("click", function () {
                    window.location.href = "/order"; // 리다이렉션할 페이지의 경로를 설정합니다.
                });
            });
        </script>
{% endblock %}

templates/food.html
<html lang="kor">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>음식 리스트</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f2f2f2;
    }

    .food-container {
      display: flex;
      flex-direction: column;
      max-width: 1000px;
      margin: 20px auto;
      background-color: #fff;
      padding: 20px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .food-item {
      display: flex;
      margin-bottom: 20px;
    }

    .food-image {
      width: 300px;
      /* 사진의 가로 크기를 조절하세요 */
      height: auto;
      margin-right: 10px;
    }

    .food-details {
      flex: 1;
    }

    .food-details h3 {
      margin-top: 0;
    }

    .food-price {
      color: #e44d26;
      /* 원하는 색상으로 변경하세요 */
      font-weight: bold;
    }

    #counter {
      font-size: 24px;
      margin: 20px;
    }

    button {
      font-size: 18px;
      margin: 5px;
      padding: 10px;
    }
  </style>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>


</head>

<body>
  <!-- flask for 반복문 -->
  {% for element in data %}
  <!-- food list-->
  <div class="food-container">
    <div class="food-item">
      <img src="{{element.furl}}" class="food-image">
      <div class="food-details">
        <h3>{{element.fname}}</h3>
        <p>{{element.finfo}}</p>
        <p class="food-price">가격: {{element.fprice}}원</p>
      </div>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal_{{ loop.index }}">
        추가
      </button>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal_{{ loop.index }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">주문</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body text-center">
          <h3>{{element.fname}}</h3>
          <div id="counter">0</div>
          <button id="increment">+</button>
          <button id="decrement">-</button>
          <!-- 음식 ID 추가 -->
          <input type="index" id="foodIdInput" value="{{ element.id }}">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-bs-dismiss="modal" onclick="submitOrder('{{ element.food_id }}')">장바구니 담기</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

  <script>
    let counterValue = 0;
    document.addEventListener("DOMContentLoaded", function () {
      // 초기값 설정
      

      // HTML 요소 가져오기
      const counterElement = document.getElementById("counter");
      const incrementButton = document.getElementById("increment");
      const decrementButton = document.getElementById("decrement");
      const counterValueInput = document.getElementById("counter");
      const orderForm = document.getElementById("orderForm");

      // 이벤트 리스너 추가
      incrementButton.addEventListener("click", function () {
        counterValue++;
        counterElement.textContent = counterValue;
        updateCounter();
      });

      decrementButton.addEventListener("click", function () {
        if (counterValue > 0) {
          counterValue--;
          counterElement.textContent = counterValue;
          updateCounter();
        }
      });

      // 카운터 업데이트 함수
      function updateCounter() {
        counterElement.textContent = counterValue;
      }
    });

    orderForm.addEventListener("submit", function () {
      // 음식 카운터 값을 input에 설정
      counterValueInput.value = counterValue;
    });


    // Cart 담기
    function submitOrder(foodId) {  
      // 음식 카운터 값을 input에 설정
      const counterValueInput = document.getElementById("counter");
      
      
      // 음식 ID 설정
      const foodIdInput = document.getElementById("foodIdInput").value;
//      foodIdInput.value = selectedFoodId;

      // store_id 설정
      const store_id = {{ store_id }}

      
      // POST 요청을 보내기
      fetch('/cart', {
          method: 'POST',
          headers: {
              'Content-Type': 'application/json',
          },
          body: JSON.stringify({
              store_id: store_id,  // 가게 ID
              food_id: foodIdInput,  // 선택한 음식의 ID
              food_count: counterValue  // 선택한 음식의 개수
          })
      }).then(response => {
          console.log(response)
          return response.json();
      }).then(data => {
          // 응답 처리 (성공 또는 실패에 따른 동작 수행)
          console.log("data")
          window.location.replace("/cart")
      });
  }
  </script>

</body>

</html>

templates/login.html
{% extends 'base.html' %} {% block head %}
<link href="../static/assets/css/login.css" rel="stylesheet" />
{% endblock %} {% block title%} 로그인 {% endblock %} {% block page_content %}

<section class="login">
  <div class="login_box">
    <div class="left">
      <div class="top_link"></div>
      <div class="contact">
        <form id="login-form" method="POST">
          <h3>SIGN IN</h3>
          <input
            type="email"
            id="email"
            name="email"
            placeholder="이메일"
            required
          />
          <input
            type="password"
            id="password"
            name="password"
            placeholder="비밀번호"
            required
          />
          <p id="error-msg" style="color: red"></p>
          <button class="submit" type="submit">로그인</button>
          <button class="submit" id="signup">회원가입</button>
        </form>
      </div>
    </div>
    <div class="right">
      <img
        src="../static/assets/img/loginimage.png"
        style="object-fit: fill; height: 600px"
        alt=""
      />
    </div>
  </div>
</section>
<script src="{{ url_for ('static', filename='assets/js/login.js') }}"></script>
{% endblock %}

templates/stores.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="../static/assets/css/store.css" />
{% endblock %}

{% block title%}
    가게
{% endblock%}

{% block page_content %}
    <div class="container mt-5" style="min-height: 300px; padding-Top: 40px;">
        <div class="row mt-5">
            {% for i in data %}
                <div class="card">
                    <img src="{{ i.image_url }}" alt="Sample Image">
                    <div class="card-content">
                        <a href="{{ url_for('food.food', store_id=i.id) }}" class="atag">{{ i.title }}</a>
                        <br></br>
                        <p class="ptag"> {{ i.contents }} </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}